[package]
name = "rust-snake"
version = "0.1.0"
authors = ["Ethan Wright <ethan@flareline.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0" }
rand = { version = "0.8.3" }
